[package]
name = 'dotshellgen'
slug = 'dotshellgen'
version = '0.1.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'Dotfile concatenation by categorization'

[run]
dependencies = ['https://github.com/hyperupcall/bash-args@v0.9.2']
sourceDirs = []
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
extglob = 'on'
globstar = 'on'
nullglob = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
