[package]
name = 'dotshellgen'
slug = 'dotshellgen'
version = '0.2.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'Dotfile concatenation by categorization'

[run]
dependencies = []
sourceDirs = []
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
extglob = 'on'
globstar = 'on'
nullglob = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
